[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "ffmpeg"]

[phases.install]
cmds = ["pip3 install -r backend/requirements.txt"]

[phases.build]
cmds = []

[start]
cmd = "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
